"""
Generates web/src/engine/gl/Shaders.ts from src/BimGo.App/Rendering/Shaders.cs (GLSL 330 core -> GLSL ES 3.00).

The shader bodies are copied unchanged; only the version line is swapped for an ES header with default precisions
(GLSL ES has no default precision for float, int or the array / shadow sampler types). Re-run after upstream changes:

    python web/scripts/port-shaders.py
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "src" / "BimGo.App" / "Rendering" / "Shaders.cs"
TARGET = ROOT / "web" / "src" / "engine" / "gl" / "Shaders.ts"

text = SOURCE.read_text(encoding="utf-8")

# const string NAME = <expression>;   where expression = parts joined by +, each a "..." or @"..." literal or a NAME
DECL = re.compile(r'(?:public|private|internal)\s+const\s+string\s+(\w+)\s*=\s*', re.M)
names = []
consts = {}
pos = 0
while True:
    m = DECL.search(text, pos)
    if not m:
        break
    name = m.group(1)
    i = m.end()
    parts = []
    while True:
        while text[i].isspace():
            i += 1
        if text.startswith('@"', i):
            j = i + 2
            buf = []
            while True:
                if text[j] == '"':
                    if text[j + 1] == '"':
                        buf.append('"')
                        j += 2
                        continue
                    break
                buf.append(text[j])
                j += 1
            parts.append(("lit", "".join(buf)))
            i = j + 1
        elif text[i] == '"':
            j = i + 1
            buf = []
            while text[j] != '"':
                if text[j] == "\\":
                    buf.append({"n": "\n", "t": "\t", '"': '"', "\\": "\\"}[text[j + 1]])
                    j += 2
                    continue
                buf.append(text[j])
                j += 1
            parts.append(("lit", "".join(buf)))
            i = j + 1
        else:
            m2 = re.compile(r"\w+").match(text, i)
            parts.append(("ref", m2.group(0)))
            i = m2.end()
        while text[i].isspace():
            i += 1
        if text[i] == "+":
            i += 1
            continue
        if text[i] == ";":
            break
        sys.exit(f"Unexpected '{text[i]}' in {name}")
    names.append(name)
    consts[name] = parts
    pos = i

VERSION = "#version 330 core\n"
HEADER = (
    "#version 300 es\n"
    "precision highp float;\n"
    "precision highp int;\n"
    "precision highp sampler2DArray;\n"
    "precision highp sampler2DArrayShadow;\n"
)


def js_string(s: str) -> str:
    return "`" + s.replace("\\", "\\\\").replace("`", "\\`").replace("${", "\\${") + "`"


out = [
    "// GENERATED by web/scripts/port-shaders.py from src/BimGo.App/Rendering/Shaders.cs. Do not edit by hand.",
    "// GLSL 330 core -> GLSL ES 3.00: the version line becomes an ES header with default precisions; bodies are unchanged.",
    "",
    f"const HEADER = {js_string(HEADER)};",
    "",
]
for name in names:
    pieces = []
    for kind, value in consts[name]:
        if kind == "ref":
            pieces.append(value)
        else:
            if value.startswith(VERSION):
                pieces.append("HEADER")
                value = value[len(VERSION):]
            elif value == VERSION.rstrip("\n") or value == VERSION:
                pieces.append("HEADER")
                continue
            if value:
                pieces.append(js_string(value))
    out.append(f"export const {name} = {' + '.join(pieces)};")
    out.append("")

TARGET.write_text("\n".join(out), encoding="utf-8", newline="\n")
print(f"Wrote {len(names)} shaders to {TARGET.relative_to(ROOT)}")
